name: Rilascio documentazione compilata

on: 
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
        - name: checkout source
          uses: actions/checkout@v4
            
        - name: check out target
          uses: actions/checkout@v4
          with: 
            name: ${{env.TARGET}}

        - name: echo
          run: tree 